name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

    - uses: actions/checkout@v2
      with:
        repository: keirf/disk-utilities
        path: disk-utilities

    - uses: actions/checkout@v2
      with:
        path: flashfloppy-hxc-file-selector

    - name: Set environment variables
      id: vars
      run: |
        cd flashfloppy-hxc-file-selector
        echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Dependency packages (apt)
      run: |
        sudo add-apt-repository ppa:vriviere/ppa
        sudo apt update
        sudo apt install -y cross-mint-essential
        sudo apt install -y autoconf bison build-essential flex gettext lhasa libgmp-dev libmpc-dev libmpfr-dev ncurses-dev rsync texinfo wget tzdata

    - name: Cache toolchain
      id: cache-toolchain
      uses: actions/cache@v2
      with:
        path: ~/cross
        key: ${{ runner.os }}

    - name: Build toolchain
      if: steps.cache-toolchain.outputs.cache-hit != 'true'
      env:
        MAKE_OPTS: -j4
        MAKE_DIR: cross
      run: |
        git config --global pull.rebase false
        export MDIR=$HOME/${MAKE_DIR}
        mkdir -p $MDIR/bin
        export PATH=$PATH:$MDIR
        mkdir ~/_tc && cd ~/_tc
        git clone https://github.com/bebbo/amiga-gcc.git
        cd amiga-gcc
        make update
        make all ${MAKE_OPTS} PREFIX=$MDIR

    - name: Build disk-analyse
      run: |
        cd disk-utilities
        make -j4 PREFIX=$HOME/install
        mkdir -p $HOME/install
        make install PREFIX=$HOME/install

    - name: Build dist
      run: |
        export LD_LIBRARY_PATH=$HOME/install/lib
        export PATH=$PATH:$HOME/install/bin:$HOME/cross/bin
        cd flashfloppy-hxc-file-selector
        make
        git rev-parse HEAD >HxC_Compat_Mode/COMMIT
        cd ..
        mkdir -p _cidist
        mv flashfloppy-hxc-file-selector/HxC_Compat_Mode _cidist/flashfloppy-hxc-file-selector.ci.${{ steps.vars.outputs.sha_short }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: flashfloppy-hxc-file-selector.ci.${{ steps.vars.outputs.sha_short }}
        path: _cidist
